name:                reflex-vty-test-host
version:             0.1.1.0
github:              "pdlla/reflex-vty-test-host"
license:             BSD3
author:              "pdlla"
maintainer:          "chippermonky@gmail.com"
copyright:           "2020 Peter Lu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            reflex host methods for testing without external events
category:            FRP, Reflex

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pdlla/reflex-vty-test-host#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
#- -Werror

default-extensions:
- ApplicativeDo
- BangPatterns
- DataKinds
- ConstraintKinds
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- NoImplicitPrelude

dependencies:
- base >= 4.7 && < 5
- reflex
- reflex-vty
- reflex-test-host
- ref-tf
- containers
- vty
- bimap


library:
  source-dirs: src

tests:
  reflex-vty-test-host-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reflex-vty-test-host
    - HUnit
    - hspec
    - hspec-contrib
